spring.application.name=SpringBootdemo

server.port=9090

management.info.env.enabled=true

info.app.name=Employee Management System
info.app.version=1.0


#management.endpoints.web.exposure.include=beans
#management.endpoints.web.exposure.include=info

#or
 management.endpoints.web.exposure.include=*
